# k8s-apps/production/httpd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fof-jack-demo-production-httpd
  namespace: argocd
spec:
  project: fof-jack-demo
  source:
    repoURL: 'https://github.com/jacksgt/app-of-apps-demo.git'
    path: charts/httpd
    targetRevision: main # For production, it is best to use a Git tag (e.g., 'v1.0.0')
    helm:
      # Environment-specific overrides for production
      values: |
        replicaCount: 3
        image:
          repository: image-registry.openshift-image-registry.svc:5000/openshift/httpd
          tag: "2.4-ubi9" # Use a specific, stable tag for production if available
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fof-jack-demo-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
