# k8s-apps/staging/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fof-jack-demo-staging-app
  namespace: fof-jack-demo-staging
spec:
  project: fof-jack-demo
  source:
    repoURL: 'https://github.com/jacksgt/app-of-apps-demo.git'
    path: charts/app
    targetRevision: HEAD
    helm:
      # Environment-specific overrides for staging
      values: |
        replicaCount: 2
        image:
          repository: docker.io/traefik/whoami
          tag: "v1.11.0"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fof-jack-demo-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
