# k8s-apps/dev/app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fof-jack-demo-dev-app
  namespace: fof-demo-dev
spec:
  project: fof-jack-demo
  source:
    repoURL: 'https://github.com/jacksgt/app-of-apps-demo.git'
    path: charts/app
    targetRevision: HEAD
    helm:
      # Environment-specific overrides for dev
      values: |
        replicaCount: 1
        image:
          repository: docker.io/traefik/whoami
          tag: "latest"
        service:
          type: ClusterIP
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: fof-jack-demo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
